on:
    push:
      branches:
        - main
  
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
  jobs:
    build:
      name: "Build"
      runs-on: [ubuntu-latest]
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: "17"
            distribution: "temurin"
            cache: maven
  
        - name: Maven package
          working-directory: ./my-app
          run: |
            # mvn package --no-transfer-progress -Dmaven.test.skip
            mvn -ntp -Dsurefire.useSystemClassLoader=false -B -U install -DskipTests=true -am
  
        - name: Create file at root
          run: touch hello.txt
  
        - name: Archive target folders
          uses: actions/upload-artifact@v4
          with:
            name: TargetFolders
            path: |
              my-app/target
              hello.txt
            retention-days: 1
  
    test:
      name: "Test"
      runs-on: [ubuntu-latest]
      needs: [build]
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: "17"
            distribution: "temurin"
            cache: maven
  
        # - name: Restore target folders
        #   uses: actions/download-artifact@v4
        #   with:
        #     name: TargetFolders
  
        - name: Maven test
          working-directory: ./my-app
          run: |
            # mvn package --no-transfer-progress
            mvn -ntp -P UnitTests test
  